### ISSUE TITLE
not an issue, but just a thought

### ISSUE THREAD

**Issue by TotallyNotAHaxxer** [b3-v3r/Hunner#53]
ive made lots of frameworks some ive posted, i think this is a nice one however just a suggestion you should add some more things, like tracers, osint, recon, web recon, social recon, and penetration testing sections!

**Comment by b3-v3r** [comment]
We can work together. Write me an email b3-v3r@protonmail.com

**Comment by TotallyNotAHaxxer** [comment]
sure thing, i will be sure to write you one. note i will not be using my main just for personal security if you are okay with that!

**Comment by b3-v3r** [comment]
Okay
