### ISSUE TITLE
Stuck at the password

### ISSUE THREAD

**Issue by hamidconrade** [b3-v3r/Hunner#63]
The YouTube video for a micro second flashed in my eyes and though I have tried and tried to replay it slowly I just can't seem to get past the 'mail.py: error' 
Someone please help. 
What is the next command after inputing the email address?
![Screenshot_20230110-202847_Termux](https://user-images.githubusercontent.com/122383368/211621519-fa0d1691-96f4-4742-872f-d87b770db5ea.jpg)

**Comment by Raesalabade** [comment]
2rpquudgpk
